import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("data/OLA_DataSet.xlsx")
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].mean())
df['Driver_Ratings'] = df['Driver_Ratings'].fillna(df['Driver_Ratings'].mean())
df = df.drop_duplicates()
plt.figure()
sns.countplot(x='Booking_Status', data=df)
plt.title("Booking Status")
plt.show()
plt.figure()
sns.countplot(x='Vehicle_Type', data=df)
plt.xticks(rotation=45)
plt.title("Vehicle Type")
plt.show()
plt.figure()
sns.histplot(df['Ride_Distance'])
plt.title("Ride Distance Distribution")
plt.show()
plt.figure()
sns.countplot(x='Payment_Method', data=df)
plt.title("Payment Method")
plt.show()
df.to_csv("data/clean_ola_data.csv", index=False)
print("EDA completed successfully")